CREATE TABLE `design_assemblies` (
  `id`           INT(11)    NOT NULL AUTO_INCREMENT,
  `order_id`     INT(11)    NOT NULL,
  `item_no`      INT(11)    NOT NULL,
  `version_no`   INT(11)    NOT NULL,
  `assembly_id`  INT(11)    NOT NULL,
  `qty`          INT(11)    NOT NULL,
  `col`          INT(11)    NOT NULL,
  `row`          INT(11)    NOT NULL,
  `shift`        INT(11)    NOT NULL,
  `stage`        INT(11)    NOT NULL,
  `is_confirmed` TINYINT(1) NOT NULL,
  `bom_id`       INT(11)    NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK7B80DE258DA3A64A` (`bom_id`)
)
  ENGINE = MyISAM;

create table design_bill_of_materials (id integer not null auto_increment, 
													is_addon boolean not null, 
													area double precision not null, 
													area_i double precision not null, 
													area_i_user double precision not null, 
													area_user double precision not null, 
													is_assembly_bom boolean not null, 
													assembly_id integer not null, 
													assembly_level_id integer not null, 
													is_buy boolean not null, 
													col integer not null, 
													cost decimal(19, 4) not null, 
													cut_length integer not null, 
													cut_length_i integer not null, 
													cut_length_i_user integer not null, 
													cut_length_user integer not null, 
													delivery integer not null, 
													depth integer not null, 
													depth_i integer not null, 
													depth_i_user integer not null, 
													depth_user integer not null, 
													description varchar(255) not null, 
													description_user varchar(255), 
													height integer not null, 
													height_i integer not null, 
													height_i_user integer not null, 
													height_user integer not null, 
													is_wild_color boolean not null, 
													is_wild_depth boolean not null, 
													is_wild_size boolean not null, 
													item_no integer not null, 
													lead_time integer not null, 
													left_angle double precision not null, 
													left_cut integer not null, 
													level integer not null, 
													level_id integer not null, 
													opening_id integer not null, 
													order_id integer not null, 
													orientation integer not null, 
													parent_assembly_id integer not null, 
													parent_col integer not null, 
													parent_row integer not null, 
													parent_rule integer not null, 
													part_family integer not null, 
													part_id integer not null, 
													position integer not null, 
													price decimal(19, 4) not null, 
													price_cat integer not null, 
													price_group integer not null, 
													price_user decimal(19, 4) not null, 
													prod_line integer not null, 
													qty integer not null, 
													qty_user double precision not null, 
													radius_1 integer not null, 
													radius_1_i integer not null, 
													radius_2 integer not null, 
													radius_2_i integer not null, 
													report integer not null, 
													req_for_stage integer not null, 
													right_angle double precision not null, 
													right_cut integer not null, row integer not null, 
													rule_no integer not null, 
													sash integer not null, 
													seg_id integer not null, 
													sequence_id integer not null, 
													shape_id integer not null, 
													station integer not null, 
													stock_code varchar(255) not null, 
													stock_code_user varchar(255), 
													supplier_id integer not null, 
													sys_assembly_id integer not null, 
													total_cost decimal(19, 4) not null, 
													total_price decimal(19, 4) not null, 
													total_price_user decimal(19, 4) not null, 
													is_track boolean not null, 
													version_id integer not null, 
													volume double precision not null, 
													volume_i double precision not null, 
													volume_i_user double precision not null, 
													volume_user double precision not null, 
													weld integer not null, 
													weld_i integer not null, 
													weld_r integer not null, 
													weld_r_i integer not null, 
													width integer not null, 
													width_i integer not null, 
													width_i_user integer not null, 
													width_user integer not null, 
													map_id integer, 
													glass_bom_id integer, 
													parent_bom_id integer, 
													job_item_id integer, 
													primary key (id)) engine=MyISAM;

CREATE TABLE `design_confirm_assemblies` (
  `id`          INT(11)      NOT NULL AUTO_INCREMENT,
  `order_id`    INT(11)      NOT NULL,
  `item_no`     INT(11)      NOT NULL,
  `version_no`  INT(11)      NOT NULL,
  `assembly_id` INT(11)      NOT NULL,
  `barcode`     VARCHAR(255) NOT NULL,
  `batched`     INT(11)      NOT NULL,
  `col`         INT(11)      NOT NULL,
  `of_qty`      INT(11)      NOT NULL,
  `place_po`    DATETIME     NULL DEFAULT NULL,
  `prod_end`    DATETIME     NULL DEFAULT NULL,
  `prod_start`  DATETIME     NULL DEFAULT NULL,
  `qty_no`      INT(11)      NOT NULL,
  `row`         INT(11)      NOT NULL,
  `shift`       INT(11)      NOT NULL,
  `stage`       INT(11)      NOT NULL,
  `sub_batched` INT(11)      NOT NULL,
  `bom_id`      INT(11)      NULL DEFAULT NULL,
  `item_bc_id`  VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK90FE4048DA3A64A` (`bom_id`)
)
  ENGINE = MyISAM;
										
create table design_construction_map (id integer not null auto_increment, 
												  level_10 integer not null, 
												  sequence_10 integer not null, 
												  level_11 integer not null, 
												  sequence_11 integer not null, 
												  level_12 integer not null, 
												  sequence_12 integer not null, 
												  level_13 integer not null, 
												  sequence_13 integer not null, 
												  level_14 integer not null, 
												  sequence_14 integer not null, 
												  level_15 integer not null, 
												  sequence_15 integer not null, 
												  level_16 integer not null, 
												  sequence_16 integer not null, 
												  level_17 integer not null, 
												  sequence_17 integer not null, 
												  level_18 integer not null, 
												  sequence_18 integer not null, 
												  level_19 integer not null, 
												  sequence_19 integer not null, 
												  level_1 integer not null, 
												  sequence_1 integer not null, 
												  level_20 integer not null, 
												  sequence_20 integer not null, 
												  level_21 integer not null, 
												  sequence_21 integer not null, 
												  level_22 integer not null, 
												  sequence_22 integer not null, 
												  level_2 integer not null, 
												  sequence_2 integer not null, 
												  level_3 integer not null, 
												  sequence_3 integer not null, 
												  level_4 integer not null, 
												  sequence_4 integer not null, 
												  level_5 integer not null, 
												  sequence_5 integer not null, 
												  level_6 integer not null, 
												  sequence_6 integer not null, 
												  level_7 integer not null, 
												  sequence_7 integer not null, 
												  level_8 integer not null, 
												  sequence_8 integer not null, 
												  level_9 integer not null, 
												  sequence_9 integer not null, 
												  assembly_level integer not null, primary key (id)) engine=MyISAM;
												  
create table design_glass (id integer not null auto_increment, 
									abbrev varchar(255) not null, 
									air_space_1 double precision not null, 
									air_space_1_i double precision not null, 
									air_space_2 double precision not null, 
									air_space_2_i double precision not null, 
									air_space_3 double precision not null, 
									air_space_3_i double precision not null, 
									assembly_level_id integer not null, 
									cavity_1_process_2 integer not null, 
									cavity_1_process_3 integer not null, 
									cavity_2_process_2 integer not null, 
									cavity_2_process_3 integer not null, 
									cavity_3_process_2 integer not null, 
									cavity_3_process_3 integer not null, 
									cavity_process_1 integer not null, 
									cavity_process_2 integer not null, 
									cavity_process_3 integer not null, 
									cost decimal(19, 4), 
									cost_actual_size boolean not null, 
									cost_group_id integer not null, 
									delivery integer not null, 
									description varchar(255) not null, 
									is_display boolean not null, 
									end_date datetime, 
									external_1_process_2 integer not null, 
									external_1_process_3 integer not null, 
									external_2_process_2 integer not null, 
									external_2_process_3 integer not null, 
									external_3_process_2 integer not null, 
									external_3_process_3 integer not null, 
									external_4_process_2 integer not null, 
									external_4_process_3 integer not null, 
									external_process_1 integer not null, 
									external_process_2 integer not null, 
									external_process_3 integer not null, 
									external_process_4 integer not null, 
									family_id integer not null, 
									film_1 integer not null, 
									film_2 integer not null, 
									film_3 integer not null, 
									film_4 integer not null, 
									gas_1 integer not null, 
									gas_2 integer not null, 
									gas_3 integer not null, 
									glass_1 integer not null, 
									glass_1_process_2 integer not null, 
									glass_1_process_3 integer not null, 
									glass_2 integer not null, 
									glass_2_process_2 integer not null, 
									glass_2_process_3 integer not null, 
									glass_3 integer not null, 
									glass_3_process_2 integer not null, 
									glass_3_process_3 integer not null, 
									glass_4 integer not null, 
									glass_4_process_2 integer not null, 
									glass_4_process_3 integer not null, 
									glass_to_spacer double precision not null, 
									glass_to_spacer_i double precision not null, 
									glazing_type integer not null, 
									height_i integer not null, 
									height_i_n integer not null, 
									height_m integer not null, 
									height_m_n integer not null, 
									insert_1_id integer not null, 
									insert_2_id integer not null, 
									insert_3_id integer not null, 
									is_custom boolean not null, 
									lead_time integer not null, 
									leaf_1 integer not null, 
									leaf_2 integer not null, 
									leaf_3 integer not null, 
									leaf_4 integer not null, 
									leaf_in integer not null, 
									leaf_no integer not null, 
									leaf_out integer not null, 
									level_id integer not null, 
									is_made_in boolean not null, 
									max_area double precision not null, 
									max_area_i double precision not null, 
									max_height integer not null, 
									max_height_i integer not null, 
									max_width integer not null, 
									max_width_i integer not null, 
									measure integer not null, 
									min_area double precision not null, 
									min_area_i double precision not null, 
									min_cost_area double precision not null, 
									min_cost_area_i double precision not null, 
									min_height integer not null, 
									min_height_i integer not null, 
									min_price decimal(19, 4), 
									min_pricing_area double precision not null, 
									min_pricing_area_i double precision not null, 
									min_width integer not null, 
									min_width_i integer not null, 
									next_item integer not null, 
									num_of_leaves integer not null, 
									parent_col integer not null, 
									part_family integer not null, 
									partner_group_id integer not null, 
									price decimal(19, 4), 
									price_actual_size boolean not null, 
									price_cat integer not null, 
									price_group integer not null, 
									price_group_id integer not null, 
									price_matrix_id integer not null, 
									price_user decimal(19, 4), 
									pricing_uom_id integer not null, 
									process_1 integer not null, 
									process_2 integer not null, 
									process_3 integer not null, 
									process_4 integer not null, 
									prod_line integer not null, 
									production_line integer not null, 
									report integer not null, 
									req_for_stage integer not null, 
									sealant_part_id integer not null, 
									sequence_id integer not null, 
									shape_id integer not null, 
									sort_seq integer not null, 
									spacer_1 integer not null, 
									spacer_2 integer not null, 
									spacer_3 integer not null, 
									spacer_thick_1 double precision not null, 
									spacer_thick_1_i double precision not null, 
									spacer_thick_2 double precision not null, 
									spacer_thick_2_i double precision not null, 
									spacer_thick_3 double precision not null, 
									spacer_thick_3_i double precision not null, 
									start_date datetime, 
									station integer not null, 
									stock_code varchar(255) not null, 
									su_id integer not null, 
									supplier_id integer not null, 
									thickness double precision not null, 
									thickness_i double precision not null, 
									ud_opening_id integer not null, 
									is_waste double precision not null, 
									wh_ratio double precision not null, 
									width_i integer not null, 
									width_i_n integer not null, 
									width_m integer not null, 
									width_m_n integer not null, 
									map_id integer, 
									job_item_id integer, primary key (id)) engine=MyISAM;
									
create table design_job_item (id integer not null auto_increment, 
										design longblob not null, 
										item_id integer not null, 
										order_id integer not null, 
										predefine_design_id integer not null, 
										predefine_series_id integer not null, 
										quantity integer not null, 
										version_id integer not null, primary key (id)) engine=MyISAM;

create table design_options (	id integer not null auto_increment, 
										adjust integer not null, 
										adjust_i integer not null, 
										answer_id integer not null, 
										assembly_level_id integer not null, 
										cost decimal(19,2) not null, 
										total_cost decimal(19,2) not null, 
										cost_uom integer not null, 
										d integer not null, 
										depth_answer integer not null, 
										depth_answer_i integer not null, 
										d_i integer not null, 
										discount_p double precision not null, 
										h integer not null, 
										h_i integer not null, 
										is_auto boolean not null, 
										is_design_all boolean not null, 
										is_design_net boolean not null, 
										is_mixed boolean not null, 
										l integer not null, 
										level_id integer not null, 
										l_i integer not null, 
										option_answers_id integer not null, 
										option_definitions_id integer not null, 
										option_definitions_type_id integer not null, 
										option_id integer not null, 
										price decimal(19,2) not null, 
										price_measure integer not null, 
										total_price decimal(19,2) not null, 
										total_price_user decimal(19,2) not null, 
										price_uom integer not null, 
										price_user decimal(19,2) not null, 
										qty_answer double precision not null, 
										is_remove boolean not null, 
										rgb_b integer not null, 
										rgb_g integer not null, 
										rgb_r integer not null, 
										rule_no integer not null, 
										seq integer not null, 
										sequence_id integer not null, 
										series_id integer not null, 
										answer_size integer not null, 
										answer_size_i integer not null, 
										text_answer varchar(255) not null, 
										w integer not null, 
										w_i integer not null, 
										map_id integer, 
										job_item_id integer, primary key (id)) engine=MyISAM;

CREATE TABLE `design_shape_notes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `level_id` INT(11) NOT NULL DEFAULT '0',
  `sequence_id` INT(11) NOT NULL DEFAULT '0',
  `assembly_level_id` INT(11) NOT NULL DEFAULT '0',
  `level_1` INT(11) NOT NULL DEFAULT '0',
  `level_2` INT(11) NOT NULL DEFAULT '0',
  `level_3` INT(11) NOT NULL DEFAULT '0',
  `level_4` INT(11) NOT NULL DEFAULT '0',
  `level_5` INT(11) NOT NULL DEFAULT '0',
  `level_6` INT(11) NOT NULL DEFAULT '0',
  `level_7` INT(11) NOT NULL DEFAULT '0',
  `level_8` INT(11) NOT NULL DEFAULT '0',
  `level_9` INT(11) NOT NULL DEFAULT '0',
  `level_10` INT(11) NOT NULL DEFAULT '0',
  `level_11` INT(11) NOT NULL DEFAULT '0',
  `level_12` INT(11) NOT NULL DEFAULT '0',
  `level_13` INT(11) NOT NULL DEFAULT '0',
  `level_14` INT(11) NOT NULL DEFAULT '0',
  `level_15` INT(11) NOT NULL DEFAULT '0',
  `level_16` INT(11) NOT NULL DEFAULT '0',
  `level_17` INT(11) NOT NULL DEFAULT '0',
  `level_18` INT(11) NOT NULL DEFAULT '0',
  `level_19` INT(11) NOT NULL DEFAULT '0',
  `level_20` INT(11) NOT NULL DEFAULT '0',
  `level_21` INT(11) NOT NULL DEFAULT '0',
  `level_22` INT(11) NOT NULL DEFAULT '0',
  `sequence_1` INT(11) NOT NULL DEFAULT '0',
  `sequence_2` INT(11) NOT NULL DEFAULT '0',
  `sequence_3` INT(11) NOT NULL DEFAULT '0',
  `sequence_4` INT(11) NOT NULL DEFAULT '0',
  `sequence_5` INT(11) NOT NULL DEFAULT '0',
  `sequence_6` INT(11) NOT NULL DEFAULT '0',
  `sequence_7` INT(11) NOT NULL DEFAULT '0',
  `sequence_8` INT(11) NOT NULL DEFAULT '0',
  `sequence_9` INT(11) NOT NULL DEFAULT '0',
  `sequence_10` INT(11) NOT NULL DEFAULT '0',
  `sequence_11` INT(11) NOT NULL DEFAULT '0',
  `sequence_12` INT(11) NOT NULL DEFAULT '0',
  `sequence_13` INT(11) NOT NULL DEFAULT '0',
  `sequence_14` INT(11) NOT NULL DEFAULT '0',
  `sequence_15` INT(11) NOT NULL DEFAULT '0',
  `sequence_16` INT(11) NOT NULL DEFAULT '0',
  `sequence_17` INT(11) NOT NULL DEFAULT '0',
  `sequence_18` INT(11) NOT NULL DEFAULT '0',
  `sequence_19` INT(11) NOT NULL DEFAULT '0',
  `sequence_20` INT(11) NOT NULL DEFAULT '0',
  `sequence_21` INT(11) NOT NULL DEFAULT '0',
  `sequence_22` INT(11) NOT NULL DEFAULT '0',
  `bom_id` INT(11) NOT NULL DEFAULT '0',
  `order_id` INT(11) NOT NULL DEFAULT '0',
  `item_no` INT(11) NOT NULL DEFAULT '0',
  `version_id` INT(11) NOT NULL DEFAULT '0',
  `rule_id` INT(11) NOT NULL DEFAULT '0',
  `series_id` INT(11) NOT NULL DEFAULT '0',
  `stock_code` VARCHAR(150) NOT NULL,
  `description` VARCHAR(150) NOT NULL,
  `value` DOUBLE NOT NULL,
  `showQty` TINYINT(1) NOT NULL DEFAULT '0',
  `job_item_id` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `FK_SHAPE_NOTES_JOB_ITEM` (`job_item_id`)
)
  COLLATE='utf8_general_ci'
  ENGINE=MyISAM;
										
alter table design_assemblies add index FK7B80DE258DA3A64A (bom_id), add constraint FK7B80DE258DA3A64A foreign key (bom_id) references design_bill_of_materials (id);
alter table design_bill_of_materials add index FK660F68BB2CE9820 (map_id), add constraint FK660F68BB2CE9820 foreign key (map_id) references design_construction_map (id);
alter table design_bill_of_materials add index FK660F68BBB159B388 (job_item_id), add constraint FK660F68BBB159B388 foreign key (job_item_id) references design_job_item (id);
alter table design_bill_of_materials add index FK660F68BBF6FEB214 (glass_bom_id), add constraint FK660F68BBF6FEB214 foreign key (glass_bom_id) references design_glass (id);
alter table design_bill_of_materials add index FK660F68BBE8F7677F (parent_bom_id), add constraint FK660F68BBE8F7677F foreign key (parent_bom_id) references design_bill_of_materials (id);
alter table design_confirm_assemblies add index FK90FE4045C2DF7F0 (parent_assembly_id), add constraint FK90FE4045C2DF7F0 foreign key (parent_assembly_id) references design_assemblies (id);
alter table design_confirm_assemblies add index FK90FE4048DA3A64A (bom_id), add constraint FK90FE4048DA3A64A foreign key (bom_id) references design_bill_of_materials (id);
alter table design_glass add index FK7B2F65BB2CE9820 (map_id), add constraint FK7B2F65BB2CE9820 foreign key (map_id) references design_construction_map (id);
alter table design_glass add index FK7B2F65BBB159B388 (job_item_id), add constraint FK7B2F65BBB159B388 foreign key (job_item_id) references design_job_item (id);
alter table design_options add index FK1BF9511D2CE9820 (map_id), add constraint FK1BF9511D2CE9820 foreign key (map_id) references design_construction_map (id);
alter table design_options add index FK1BF9511DB159B388 (job_item_id), add constraint FK1BF9511DB159B388 foreign key (job_item_id) references design_job_item (id);
alter table design_shape_notes add index FK_SHAPE_NOTES_JOB_ITEM (job_item_id), add constraint FK_SHAPE_NOTES_JOB_ITEM foreign key (job_item_id) references design_job_item (id);




