package openjanela.commons.util;

import javax.swing.*;
import java.util.HashMap;
import java.util.Map;

/**
 * Copyright (c) 2012, OpenJanela. All rights reserved.
 * <p/>
 * This class load all resources images from <p>openjanela-resources</p> module.
 * User: EMontenegro
 * Date: 02-20-12
 * Time: 04:18 PM
 */
public class ResourcesUtil {

    //Image icon map
    private static Map<String, ImageIcon> imageIconMap;

    public static Map<String, ImageIcon> getImageIconMap() {
        if (imageIconMap == null)
            imageIconMap = loadImageIconMap();

        return imageIconMap;
    }

    /**
     * Load resources with ImageIcon object to use in main frame
     *
     * @return Map<String, ImageIcon>
     */
    private static Map<String, ImageIcon> loadImageIconMap() {

        Map<String, ImageIcon> imageIconMap = new HashMap<String, ImageIcon>();

        imageIconMap.put("openJanelaIcon", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/oj16x16.png")));
        imageIconMap.put("designsearch", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/designsearch.png")));
        imageIconMap.put("designsave", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/designsave.png")));
        imageIconMap.put("openJanelaIcon", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/oj16x16.png")));
        imageIconMap.put("pos1In", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/pos1In.png")));
        imageIconMap.put("pos2Mid", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/pos2Mid.png")));
        imageIconMap.put("pos3Out", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/pos3Out.png")));
        imageIconMap.put("error", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/error.png")));
        imageIconMap.put("bayC1", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/bayC1.png")));
        imageIconMap.put("bayC2", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/bayC2.png")));
        imageIconMap.put("undo", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/undo.png")));
        imageIconMap.put("tip", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/tip.png")));
        imageIconMap.put("add", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/add.png")));
        imageIconMap.put("add", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/add.png")));
        imageIconMap.put("add", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/add.png")));
        imageIconMap.put("grids16", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/grids16.png")));
        imageIconMap.put("glass16", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/glass16.png")));
        imageIconMap.put("designFunction", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/design.png")));
        imageIconMap.put("options", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/options.png")));
        imageIconMap.put("add", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/add.png")));
        imageIconMap.put("change", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/change.png")));
        imageIconMap.put("set", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/set.png")));
        imageIconMap.put("goset", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/set.png")));
        imageIconMap.put("save", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/save.png")));
        imageIconMap.put("cancel", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/cancelstop.png")));
        imageIconMap.put("couplermullion", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/couplermullion.png")));
        imageIconMap.put("shapes", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/shapes.png")));
        imageIconMap.put("subFrame", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/subFrame.png")));
        imageIconMap.put("entry", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/entry.png")));
        imageIconMap.put("doors", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/doors.png")));
        imageIconMap.put("windows", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/windows.png")));
        imageIconMap.put("standard", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/standards.png")));
        imageIconMap.put("couplers", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/couplers.png")));
        imageIconMap.put("mullions", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/mullions.png")));
        imageIconMap.put("view", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/view.png")));
        imageIconMap.put("search", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/search.png")));
        imageIconMap.put("dimensioning", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/dimensioning.png")));
        imageIconMap.put("haf", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/haf.png")));
        imageIconMap.put("viewIn", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/viewIn.png")));
        imageIconMap.put("viewOut", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/viewOut.png")));
        imageIconMap.put("openings", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/openings.png")));
        imageIconMap.put("editprofiles", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/editprofiles.png")));
        imageIconMap.put("overallShape", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/overallShape.png")));
        imageIconMap.put("frameShape", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/frameShape.png")));
        imageIconMap.put("overallShapeSelected", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/overallShapeSelected.png")));
        imageIconMap.put("frameShapeSelected", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/frameShapeSelected.png")));
        imageIconMap.put("overallShapeUnselected", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/overallShapeUnselected.png")));
        imageIconMap.put("frameShapeUnselected", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/frameShapeUnselected.png")));
        imageIconMap.put("vc", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/VCoupler.png")));
        imageIconMap.put("hc", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/HCoupler.png")));
        imageIconMap.put("vm", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/VMullion.png")));
        imageIconMap.put("hm", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/HMullion.png")));
        imageIconMap.put("flat", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/flat.png")));
        imageIconMap.put("bay", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/bay.png")));
        imageIconMap.put("bow", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/bow.png")));
        imageIconMap.put("custom", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/custom.png")));
        imageIconMap.put("sashdims", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/sashdims.png")));
        imageIconMap.put("switchsash", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/switchsash.png")));
        imageIconMap.put("framelevel", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/framelevel.png")));
        imageIconMap.put("sublevel", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/sublevel.png")));
        imageIconMap.put("rightbotend", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/rightbotend.png")));
        imageIconMap.put("lefttopend", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/lefttopend.png")));
        imageIconMap.put("part", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/part.png")));
        imageIconMap.put("profileshape", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/profileshape.png")));
        imageIconMap.put("vandhgrids", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/vandhgrids.png")));
        imageIconMap.put("vgrid", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/vgrid.png")));
        imageIconMap.put("hgrid", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/hgrid.png")));
        imageIconMap.put("radiusgrids", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/radiusgrids.png")));
        imageIconMap.put("spokes", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/spokes.png")));
        imageIconMap.put("allglass", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/allglass.png")));
        imageIconMap.put("oneglass", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/oneglass.png")));
        imageIconMap.put("glassClass", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/glassClass.png")));
        imageIconMap.put("width", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/width.png")));
        imageIconMap.put("oswidth", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/oswidth.png")));
        imageIconMap.put("height", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/height.png")));
        imageIconMap.put("osheight", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/osheight.png")));
        imageIconMap.put("itemno", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/itemno.png")));
        imageIconMap.put("description", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/description.png")));
        imageIconMap.put("qty", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/qty.png")));
        imageIconMap.put("location", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/location.png")));
        imageIconMap.put("supplier", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/supplier.png")));
        imageIconMap.put("series", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/series.png")));
        imageIconMap.put("ref1", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/ref1.png")));
        imageIconMap.put("ref2", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/ref2.png")));
        imageIconMap.put("uom", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/uom.png")));
        imageIconMap.put("elevation", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/elevation.png")));
        imageIconMap.put("cost", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/cost.png")));
        imageIconMap.put("price", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/price.png")));
        imageIconMap.put("note", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/notes.png")));
        imageIconMap.put("addons", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/addons.png")));
        imageIconMap.put("nominalframe", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/nominalframe.png")));
        imageIconMap.put("actualframe", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/actualframe.png")));
        imageIconMap.put("bkgrd", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/bkgrd.png")));
        imageIconMap.put("nominalopening", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/nominalopening.png")));
        imageIconMap.put("actualopening", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/actualopening.png")));
        imageIconMap.put("glass", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/glass.png")));
        imageIconMap.put("dlo", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/dlo.png")));
        imageIconMap.put("grids", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/grids.png")));
        imageIconMap.put("toptofloor", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/toptofloor.png")));
        imageIconMap.put("midtofloor", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/midtofloor.png")));
        imageIconMap.put("bottofloor", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/bottofloor.png")));
        imageIconMap.put("subsash", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/subsash.png")));
        imageIconMap.put("imagenogrid", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/NoGrids.png")));
        imageIconMap.put("imageremoveGrid", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/RemoveGrid.png")));
        imageIconMap.put("imagecutGrid", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/Cut16.png")));
        imageIconMap.put("imagechangmaterH", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/ChangeMasterH.png")));
        imageIconMap.put("imagechangmaterV", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/ChangeMasterV.png")));
        imageIconMap.put("imageaddGrid", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/AddGrid.png")));
        imageIconMap.put("imageNoGrids", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/NumGrids.png")));
        imageIconMap.put("cutCursor", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/cutCursor.png")));
        imageIconMap.put("hMullionCursor", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/hMullionCursor.png")));
        imageIconMap.put("vMullionCursor", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/vMullionCursor.png")));
        imageIconMap.put("hCouplerCursor", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/hCouplerCursor.png")));
        imageIconMap.put("vCouplerCursor", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/vCouplerCursor.png")));
        imageIconMap.put("shape1", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/1.png")));
        imageIconMap.put("shape10", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/10.png")));
        imageIconMap.put("shape90", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/90.png")));
        imageIconMap.put("shape91", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/91.png")));
        imageIconMap.put("shape92", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/92.png")));
        imageIconMap.put("shape93", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/93.png")));
        imageIconMap.put("shape100", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/100.png")));
        imageIconMap.put("shape101", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/101.png")));
        imageIconMap.put("shape102", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/102.png")));
        imageIconMap.put("shape103", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/103.png")));
        imageIconMap.put("shape104", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/104.png")));
        imageIconMap.put("shape105", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/105.png")));
        imageIconMap.put("shape106", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/106.png")));
        imageIconMap.put("shape107", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/107.png")));
        imageIconMap.put("shape108", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/108.png")));
        imageIconMap.put("shape109", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/109.png")));
        imageIconMap.put("shape110", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/110.png")));
        imageIconMap.put("shape111", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/111.png")));
        imageIconMap.put("shape112", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/112.png")));
        imageIconMap.put("shape113", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/113.png")));
        imageIconMap.put("shape114", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/114.png")));
        imageIconMap.put("shape115", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/115.png")));
        imageIconMap.put("shape150", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/150.png")));
        imageIconMap.put("shape151", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/151.png")));
        imageIconMap.put("shape152", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/152.png")));
        imageIconMap.put("shape153", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/153.png")));
        imageIconMap.put("shape154", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/154.png")));
        imageIconMap.put("shape155", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/155.png")));
        imageIconMap.put("shape156", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/156.png")));
        imageIconMap.put("shape157", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/157.png")));
        imageIconMap.put("shape160", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/160.png")));
        imageIconMap.put("shape161", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/161.png")));
        imageIconMap.put("shape162", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/162.png")));
        imageIconMap.put("shape163", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/163.png")));
        imageIconMap.put("shape165", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/165.png")));
        imageIconMap.put("shape166", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/165.png")));
        imageIconMap.put("shape167", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/165.png")));
        imageIconMap.put("shape168", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/165.png")));
        imageIconMap.put("shape200", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/200.png")));
        imageIconMap.put("shape201", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/201.png")));
        imageIconMap.put("shape202", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/202.png")));
        imageIconMap.put("shape203", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/203.png")));
        imageIconMap.put("shape204", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/204.png")));
        imageIconMap.put("shape205", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/205.png")));
        imageIconMap.put("shape206", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/206.png")));
        imageIconMap.put("shape207", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/207.png")));
        imageIconMap.put("shape208", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/208.png")));
        imageIconMap.put("shape209", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/209.png")));
        imageIconMap.put("shape210", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/210.png")));
        imageIconMap.put("shape211", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/211.png")));
        imageIconMap.put("shape212", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/212.png")));
        imageIconMap.put("shape213", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/213.png")));
        imageIconMap.put("shape214", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/214.png")));
        imageIconMap.put("shape215", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/215.png")));
        imageIconMap.put("shape216", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/216.png")));
        imageIconMap.put("shape217", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/217.png")));
        imageIconMap.put("shape218", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/218.png")));
        imageIconMap.put("shape219", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/219.png")));
        imageIconMap.put("shape300", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/300.png")));
        imageIconMap.put("shape301", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/301.png")));
        imageIconMap.put("shape302", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/302.png")));
        imageIconMap.put("shape303", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/303.png")));
        imageIconMap.put("shape304", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/304.png")));
        imageIconMap.put("shape305", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/305.png")));
        imageIconMap.put("shape306", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/306.png")));
        imageIconMap.put("shape307", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/307.png")));
        imageIconMap.put("shape308", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/308.png")));
        imageIconMap.put("shape309", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/309.png")));
        imageIconMap.put("shape310", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/310.png")));
        imageIconMap.put("shape311", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/311.png")));
        imageIconMap.put("shape312", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/312.png")));
        imageIconMap.put("shape313", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/313.png")));
        imageIconMap.put("shape314", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/314.png")));
        imageIconMap.put("shape315", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/315.png")));
        imageIconMap.put("shape316", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/316.png")));
        imageIconMap.put("shape317", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/317.png")));
        imageIconMap.put("shape318", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/318.png")));
        imageIconMap.put("shape319", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/319.png")));
        imageIconMap.put("shape400", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/400.png")));
        imageIconMap.put("shape401", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/401.png")));
        imageIconMap.put("shape402", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/402.png")));
        imageIconMap.put("shape450", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/450.png")));
        imageIconMap.put("shape453", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/453.png")));
        imageIconMap.put("shape700", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/700.png")));
        imageIconMap.put("shape701", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/701.png")));
        imageIconMap.put("shape702", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/702.png")));
        imageIconMap.put("shape703", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/703.png")));
        imageIconMap.put("shape704", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/704.png")));
        imageIconMap.put("shape705", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/705.png")));
        imageIconMap.put("shape706", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/706.png")));
        imageIconMap.put("shape707", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/707.png")));
        imageIconMap.put("shape800", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/800.png")));
        imageIconMap.put("shape801", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/801.png")));
        imageIconMap.put("shape802", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/802.png")));
        imageIconMap.put("op1", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/1op.png")));
        imageIconMap.put("op2", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/2op.png")));
        imageIconMap.put("op3", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/3op.png")));
        imageIconMap.put("op4", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/4op.png")));
        imageIconMap.put("op5", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/5op.png")));
        imageIconMap.put("op6", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/6op.png")));
        imageIconMap.put("op7", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/7op.png")));
        imageIconMap.put("op8", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/8op.png")));
        imageIconMap.put("op9", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/9op.png")));
        imageIconMap.put("op10", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/10op.png")));
        imageIconMap.put("op11", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/11op.png")));
        imageIconMap.put("op12", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/12op.png")));
        imageIconMap.put("op13", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/13op.png")));
        imageIconMap.put("op14", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/14op.png")));
        imageIconMap.put("op15", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/15op.png")));
        imageIconMap.put("op16", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/16op.png")));
        imageIconMap.put("op17", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/17op.png")));
        imageIconMap.put("op211", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/211op.png")));
        imageIconMap.put("op212", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/212op.png")));
        imageIconMap.put("op213", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/213op.png")));
        imageIconMap.put("op214", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/214op.png")));
        imageIconMap.put("op215", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/215op.png")));
        imageIconMap.put("op216", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/216op.png")));
        imageIconMap.put("op217", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/217op.png")));
        imageIconMap.put("op18", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/18op.png")));
        imageIconMap.put("op218", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/18op.png")));
        imageIconMap.put("op21", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/21op.png")));
        imageIconMap.put("op22", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/22op.png")));
        imageIconMap.put("op23", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/23op.png")));
        imageIconMap.put("op24", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/24op.png")));
        imageIconMap.put("op221", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/221op.png")));
        imageIconMap.put("op222", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/222op.png")));
        imageIconMap.put("op223", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/223op.png")));
        imageIconMap.put("op224", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/224op.png")));
        imageIconMap.put("op31", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/31op.png")));
        imageIconMap.put("op32", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/32op.png")));
        imageIconMap.put("op231", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/231op.png")));
        imageIconMap.put("op232", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/232op.png")));
        imageIconMap.put("op41", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/41op.png")));
        imageIconMap.put("op42", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/42op.png")));
        imageIconMap.put("op43", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/43op.png")));
        imageIconMap.put("op44", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/44op.png")));
        imageIconMap.put("op243", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/243op.png")));
        imageIconMap.put("op244", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/244op.png")));
        imageIconMap.put("op51", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/51op.png")));
        imageIconMap.put("op52", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/52op.png")));
        imageIconMap.put("op61", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/61op.png")));
        imageIconMap.put("op71", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/71op.png")));
        imageIconMap.put("op72", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/72op.png")));
        imageIconMap.put("op73", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/73op.png")));
        imageIconMap.put("op76", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/76op.png")));
        imageIconMap.put("op77", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/77op.png")));
        imageIconMap.put("op78", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/78op.png")));
        imageIconMap.put("op271", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/271op.png")));
        imageIconMap.put("op272", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/272op.png")));
        imageIconMap.put("op273", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/273op.png")));
        imageIconMap.put("op276", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/276op.png")));
        imageIconMap.put("op277", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/277op.png")));
        imageIconMap.put("op278", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/278op.png")));
        imageIconMap.put("op291", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/291op.png")));
        imageIconMap.put("op292", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/292op.png")));
        imageIconMap.put("op293", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/293op.png")));
        imageIconMap.put("op301", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/301op.png")));
        imageIconMap.put("op302", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/302op.png")));
        imageIconMap.put("op303", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/303op.png")));
        imageIconMap.put("op311", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/311op.png")));
        imageIconMap.put("op312", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/312op.png")));
        imageIconMap.put("op313", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/313op.png")));
        imageIconMap.put("3sided", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/3sides.png")));
        imageIconMap.put("4sided", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/4sides.png")));
        imageIconMap.put("5sided", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/5sides.png")));
        imageIconMap.put("6sided", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/6sides.png")));
        imageIconMap.put("roundtop", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/roundtop.png")));
        imageIconMap.put("archtop", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/archtop.png")));
        imageIconMap.put("gothictop", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/gothictop.png")));
        imageIconMap.put("oddshape", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/oddshapes.png")));
        imageIconMap.put("1ls", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/1ls.png")));
        imageIconMap.put("2ls", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/2ls.png")));
        imageIconMap.put("ns", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/ns.png")));
        imageIconMap.put("outswing", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/outswing.png")));
        imageIconMap.put("inswing", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/inswing.png")));
        imageIconMap.put("folding", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/folding.png")));
        imageIconMap.put("transoms", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/transoms.png")));
        imageIconMap.put("sidelights", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/sidelights.png")));
        imageIconMap.put("kp", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/kp.png")));
        imageIconMap.put("std", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/std.png")));
        imageIconMap.put("stdset", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/stdset.png")));
        imageIconMap.put("baydetails", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/baydetails.png")));
        imageIconMap.put("bowdetails", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/bowdetails.png")));
        imageIconMap.put("flatdetails", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/flatdetails.png")));
        imageIconMap.put("flatwidth", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/flatwidth.png")));
        imageIconMap.put("customdetails", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/customdetails.png")));
        imageIconMap.put("refresh", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/refresh.png")));
        imageIconMap.put("equalize", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/equalize16.png")));
        imageIconMap.put("equalizeH", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/equalize16H.png")));
        imageIconMap.put("alignV", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/alignV16.png")));
        imageIconMap.put("alignH", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/alignH16.png")));
        imageIconMap.put("edit", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/edit.png")));
        imageIconMap.put("extend", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/extend.png")));
        imageIconMap.put("removeM", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/removeM.png")));
        imageIconMap.put("abcDim", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/abc_dims.png")));
        imageIconMap.put("noLeafsBefore", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/noOfLeafsBeforeOpen.png")));
        imageIconMap.put("noLeafs", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/noOfLeafs.png")));

        
        
        
        imageIconMap.put("abcDH", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/abc_dh.png")));
        imageIconMap.put("abcSH", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/abc_sh.png")));
        imageIconMap.put("abcSSL", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/abc_ssl.png")));
        imageIconMap.put("abcSSR", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/abc_ssr.png")));
        imageIconMap.put("abc2LP", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/abc_2lp.png")));
        imageIconMap.put("abc3LS", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/abc_3ls.png")));
        imageIconMap.put("abc4LS", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/abc_4ls.png")));
        imageIconMap.put("abcCLS", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/abc_cls.png")));
        imageIconMap.put("abcDLS", new ImageIcon(ResourcesUtil.class.getResource("/openjanela/resources/icons/abc_dls.png")));
        
        return imageIconMap;
    }
}
